### ISSUE TITLE
cron unable to find documents !

### ISSUE THREAD

**Issue by rupinder1133** [xpepermint/mongoose-cron#9]
Task.createCron().start(); gives error
`Unhandled rejection TypeError: Cannot read property 'update' of null
at promise.then.res (/Users/rupinder/heyzot/two/node_modules/mongoose-cron/lib/cron.js:166:21)
at process._tickCallback (internal/process/next_tick.js:109:7)`

**Comment by xpepermint** [comment]
If possible, please use [mongodb-cron](https://github.com/xpepermint/mongodb-cron) package. PR for this package is also welcome.
